FROM node:22-alpine AS prepare
WORKDIR /app
COPY . ./

ARG AUTH_SECRET
ARG SMS_API_KEY
ARG SMS_SERVICE_URI
ARG AUTH_YANDEX_ID
ARG AUTH_YANDEX_SECRET
ARG DATABASE_HOST
ARG DATABASE_NAME
ARG DATABASE_USER
ARG DATABASE_PASSWORD
ARG AUTH_GOOGLE_ID
ARG AUTH_GOOGLE_SECRET
ARG EMAIL_SERVER
ARG EMAIL_FROM

RUN touch ./.env.local
ENV SMS_API_KEY=$SMS_API_KEY
ENV SMS_SERVICE_URI=$SMS_SERVICE_URI
ENV AUTH_YANDEX_ID=$AUTH_YANDEX_ID
ENV AUTH_YANDEX_SECRET=$AUTH_YANDEX_SECRET
ENV DATABASE_HOST=$DATABASE_HOST
ENV DATABASE_NAME=$DATABASE_NAME
ENV DATABASE_USER=$DATABASE_USER
ENV DATABASE_PASSWORD=$DATABASE_PASSWORD
ENV AUTH_GOOGLE_ID=$AUTH_GOOGLE_ID
ENV AUTH_GOOGLE_SECRET=$AUTH_GOOGLE_SECRET
ENV EMAIL_SERVER=$EMAIL_SERVER
ENV EMAIL_FROM=$EMAIL_FROM
ENV AUTH_SECRET=$AUTH_SECRET
ENV AUTH_TRUST_HOST=true

RUN echo "SMS_API_KEY=$SMS_API_KEY" >> .env.local
RUN echo "SMS_SERVICE_URI=$SMS_SERVICE_URI" >> .env.local
RUN echo "AUTH_YANDEX_ID=$AUTH_YANDEX_ID" >> .env.local
RUN echo "AUTH_YANDEX_SECRET=$AUTH_YANDEX_SECRET" >> .env.local
RUN echo "DATABASE_HOST=$DATABASE_HOST" >> .env.local
RUN echo "DATABASE_NAME=$DATABASE_NAME" >> .env.local
RUN echo "DATABASE_USER=$DATABASE_USER" >> .env.local
RUN echo "DATABASE_PASSWORD=$DATABASE_PASSWORD" >> .env.local
RUN echo "AUTH_GOOGLE_ID=$AUTH_GOOGLE_ID" >> .env.local
RUN echo "AUTH_GOOGLE_SECRET=$AUTH_GOOGLE_SECRET" >> .env.local
RUN echo "EMAIL_SERVER=$EMAIL_SERVER" >> .env.local
RUN echo "EMAIL_FROM=$EMAIL_FROM" >> .env.local
RUN echo "AUTH_SECRET=$AUTH_SECRET" >> .env.local
RUN echo "AUTH_TRUST_HOST=true" >> .env.local

RUN ls -a
RUN cat .env.local

RUN yarn
FROM prepare AS build
RUN yarn build
FROM node:22-alpine  AS front
WORKDIR /app
COPY --from=build /app ./
RUN ls
EXPOSE 3000
CMD ["yarn", "start"]
