name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker/login-action@v3
      name: Login to Docker Hub
      with:
        username: ${{ vars.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - uses: docker/build-push-action@v6.15.0
      name: Build and push Docker image
      with:
        push: true
        tags: resg/salon:latest
  
